<?php

/**
 * BaseCategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $category_name
 * @property Doctrine_Collection $PostsCategory
 * 
 * @method string              getCategoryName()  Returns the current record's "category_name" value
 * @method Doctrine_Collection getPostsCategory() Returns the current record's "PostsCategory" collection
 * @method Category            setCategoryName()  Sets the current record's "category_name" value
 * @method Category            setPostsCategory() Sets the current record's "PostsCategory" collection
 * 
 * @package    blog
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCategory extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('category');
        $this->hasColumn('category_name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Post as PostsCategory', array(
             'local' => 'id',
             'foreign' => 'category_id'));
    }
}