<?php

/**
 * BaseTags
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $tag_name
 * @property Doctrine_Collection $Posts
 * @property Doctrine_Collection $PostsTags
 * 
 * @method string              getTagName()   Returns the current record's "tag_name" value
 * @method Doctrine_Collection getPosts()     Returns the current record's "Posts" collection
 * @method Doctrine_Collection getPostsTags() Returns the current record's "PostsTags" collection
 * @method Tags                setTagName()   Sets the current record's "tag_name" value
 * @method Tags                setPosts()     Sets the current record's "Posts" collection
 * @method Tags                setPostsTags() Sets the current record's "PostsTags" collection
 * 
 * @package    blog
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTags extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tags');
        $this->hasColumn('tag_name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Posts', array(
             'refClass' => 'PostsTags',
             'local' => 'tags_id',
             'foreign' => 'posts_id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('PostsTags', array(
             'local' => 'id',
             'foreign' => 'tags_id'));
    }
}