<?php

/**
 * BaseComments
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $user_id
 * @property integer $post_id
 * @property string $comment
 * @property Posts $Posts
 * @property sfGuardUser $sfGuardUser
 * 
 * @method integer     getUserId()      Returns the current record's "user_id" value
 * @method integer     getPostId()      Returns the current record's "post_id" value
 * @method string      getComment()     Returns the current record's "comment" value
 * @method Posts       getPosts()       Returns the current record's "Posts" value
 * @method sfGuardUser getSfGuardUser() Returns the current record's "sfGuardUser" value
 * @method Comments    setUserId()      Sets the current record's "user_id" value
 * @method Comments    setPostId()      Sets the current record's "post_id" value
 * @method Comments    setComment()     Sets the current record's "comment" value
 * @method Comments    setPosts()       Sets the current record's "Posts" value
 * @method Comments    setSfGuardUser() Sets the current record's "sfGuardUser" value
 * 
 * @package    blog
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseComments extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('comments');
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('post_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('comment', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));

        $this->option('charset', 'utf8');
        $this->option('collate', 'utf8_general_ci');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Posts', array(
             'local' => 'post_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('sfGuardUser', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}