<?php

/**
 * BasePost
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $category_id
 * @property string $title
 * @property string $short_text
 * @property string $full_text
 * @property string $thumb
 * @property string $tags
 * @property Category $Category
 * @property Doctrine_Collection $CommentsPost
 * 
 * @method integer             getCategoryId()   Returns the current record's "category_id" value
 * @method string              getTitle()        Returns the current record's "title" value
 * @method string              getShortText()    Returns the current record's "short_text" value
 * @method string              getFullText()     Returns the current record's "full_text" value
 * @method string              getThumb()        Returns the current record's "thumb" value
 * @method string              getTags()         Returns the current record's "tags" value
 * @method Category            getCategory()     Returns the current record's "Category" value
 * @method Doctrine_Collection getCommentsPost() Returns the current record's "CommentsPost" collection
 * @method Post                setCategoryId()   Sets the current record's "category_id" value
 * @method Post                setTitle()        Sets the current record's "title" value
 * @method Post                setShortText()    Sets the current record's "short_text" value
 * @method Post                setFullText()     Sets the current record's "full_text" value
 * @method Post                setThumb()        Sets the current record's "thumb" value
 * @method Post                setTags()         Sets the current record's "tags" value
 * @method Post                setCategory()     Sets the current record's "Category" value
 * @method Post                setCommentsPost() Sets the current record's "CommentsPost" collection
 * 
 * @package    blog
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePost extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('post');
        $this->hasColumn('category_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('title', 'string', 60, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 60,
             ));
        $this->hasColumn('short_text', 'string', 500, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 500,
             ));
        $this->hasColumn('full_text', 'string', 10000, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 10000,
             ));
        $this->hasColumn('thumb', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('tags', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Category', array(
             'local' => 'category_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('Comment as CommentsPost', array(
             'local' => 'id',
             'foreign' => 'post_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}