<?php

/**
 * BaseCategories
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $category_name
 * @property Doctrine_Collection $PostsCategory
 * 
 * @method string              getCategoryName()  Returns the current record's "category_name" value
 * @method Doctrine_Collection getPostsCategory() Returns the current record's "PostsCategory" collection
 * @method Categories          setCategoryName()  Sets the current record's "category_name" value
 * @method Categories          setPostsCategory() Sets the current record's "PostsCategory" collection
 * 
 * @package    blog
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCategories extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('categories');
        $this->hasColumn('category_name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));

        $this->option('charset', 'utf8');
        $this->option('collate', 'utf8_general_ci');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Posts as PostsCategory', array(
             'local' => 'id',
             'foreign' => 'category_id'));

        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'unique' => true,
             'fields' => 
             array(
              0 => 'category_name',
             ),
             'canUpdate' => true,
             'builder' => 
             array(
              0 => 'slugifyClass',
              1 => 'Slugify',
             ),
             ));
        $this->actAs($sluggable0);
    }
}