<?php

/**
 * BaseComment
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $user_id
 * @property integer $post_id
 * @property string $comment_text
 * @property Post $Post
 * @property sfGuardUser $sfGuardUser
 * 
 * @method integer     getUserId()       Returns the current record's "user_id" value
 * @method integer     getPostId()       Returns the current record's "post_id" value
 * @method string      getCommentText()  Returns the current record's "comment_text" value
 * @method Post        getPost()         Returns the current record's "Post" value
 * @method sfGuardUser getSfGuardUser()  Returns the current record's "sfGuardUser" value
 * @method Comment     setUserId()       Sets the current record's "user_id" value
 * @method Comment     setPostId()       Sets the current record's "post_id" value
 * @method Comment     setCommentText()  Sets the current record's "comment_text" value
 * @method Comment     setPost()         Sets the current record's "Post" value
 * @method Comment     setSfGuardUser()  Sets the current record's "sfGuardUser" value
 * 
 * @package    blog
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseComment extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('comment');
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('post_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('comment_text', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Post', array(
             'local' => 'post_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('sfGuardUser', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}