<?php

/**
 * BasePostsTags
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $posts_id
 * @property integer $tags_id
 * @property Posts $Posts
 * @property Tags $Tags
 * 
 * @method integer   getPostsId()  Returns the current record's "posts_id" value
 * @method integer   getTagsId()   Returns the current record's "tags_id" value
 * @method Posts     getPosts()    Returns the current record's "Posts" value
 * @method Tags      getTags()     Returns the current record's "Tags" value
 * @method PostsTags setPostsId()  Sets the current record's "posts_id" value
 * @method PostsTags setTagsId()   Sets the current record's "tags_id" value
 * @method PostsTags setPosts()    Sets the current record's "Posts" value
 * @method PostsTags setTags()     Sets the current record's "Tags" value
 * 
 * @package    blog
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePostsTags extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('posts_tags');
        $this->hasColumn('posts_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('tags_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));

        $this->option('charset', 'utf8');
        $this->option('collate', 'utf8_general_ci');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Posts', array(
             'local' => 'posts_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Tags', array(
             'local' => 'tags_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}