<?php

/**
 * CategoriesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CategoriesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CategoriesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Categories');
    }
    public function getCategoriesKeys(){
        $q = Doctrine_Query::create()
            ->from('Categories c');
        $r = $q->execute();
        $catsName = array();
        foreach($r as $row)
            $catsName[$row->getId()] = $row->getCategoryName();
        return $catsName;
    }
}