<?php

/**
 * PostsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PostsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PostsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Posts');
    }
    public function retrieveBackendPostList(Doctrine_Query $q)
    {
        $rootAlias = $q->getRootAlias();
        $q->leftJoin($rootAlias . '.Categories c');
        return $q;
    }

    public function getAllPostsQuery(){
        return Doctrine_Query::create()
            ->from('Posts p')
            ->orderBy('p.updated_at desc');
    }

    public function getAllPosts(){
        return $this->getAllPostsQuery()->execute();
    }

    public function getPostsInCategoryQuery($cat_id){
        return Doctrine_Query::create()
            ->from('Posts p')
            ->where("p.category_id = $cat_id")
            ->orderBy('p.updated_at desc');

    }
    public function getPostsInCategory($cat_id){
        return $this->getPostsInCategoryQuery($cat_id)->execute();
    }
    public function getPostsByTagQuery($tag_id){

        return Doctrine_Query::create()
            ->from('Posts p')
            ->where('p.id IN (SELECT pt.posts_id FROM PostsTags pt WHERE pt.tags_id = ?)', $tag_id)
            ->orderBy('p.updated_at desc');
    }
    public function getPostsByTag($tag_id){
        return $this->getPostsByTagQuery($tag_id)->execute();
    }

    public function getLatestPost(){
        $r = Doctrine_Query::create()
            ->from('Posts p')
            ->orderBy('p.updated_at desc')->execute();
        return $r[0];
    }

    public function getComments($post_id){
        $q = Doctrine_Query::create()
            ->from("Comments c")
            ->innerJoin("c.sfGuardUser u")
            ->innerJoin("c.Posts p")
            ->where("p.id = ".$post_id);
        $r = $q->execute();
        return $r;

    }
}