<?php

/**
 * PostsTagsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PostsTagsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PostsTagsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PostsTags');
    }

}