<?php

/**
 * sfGuardUserProfileTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class sfGuardUserProfileTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object sfGuardUserProfileTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('sfGuardUserProfile');
    }

    public function getProfile(){
        $user_id = sfContext::getInstance()->getUser()->getUserId();
        $q = Doctrine_Query::create()
            ->from('sfGuardUserProfile p')
            ->where('p.user_id = ?', $user_id);
        return $q->execute()->getFirst();
    }
}