<?php

/**
 * TagsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TagsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TagsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Tags');
    }

    public function getTagsName(){
        $q = Doctrine_Query::create()
            ->from('Tags t');
        $r = $q->execute();
        $tagsName = array();
        foreach($r as $row)
            $tagsName[$row->getTagName()] = $row->getTagName();
        return $tagsName;
    }
    public function getTagsKeys(){
        $q = Doctrine_Query::create()
            ->from('Tags t');
        $r = $q->execute();
        $tagsName = array();
        foreach($r as $row)
            $tagsName[$row->getId()] = $row->getTagName();
        return $tagsName;
    }

}