# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
posts:
  class: sfDoctrineRouteCollection
  options:
    model:                Posts
    module:               posts
    prefix_path:          /posts
    column:               id
    with_wildcard_routes: true

posts_show_full:
    url: /post/:id/:title_slug
    param: { module: posts, action: showFull }

posts_show_tag:
    url: /tag/:id/:tag_slug
    param: { module: posts, action: showTag }

posts_delete_comment:
    url: /comment/:id
    param: { module: posts, action: deleteComment }

category_show:
    url: /category/:id/:category_slug
    param: { module: posts, action: showCategory }

profile:
  class: sfDoctrineRouteCollection
  options:
    model:                sfGuardUserProfile
    module:               profile
    prefix_path:          /profile
    column:               id
    with_wildcard_routes: true

sf_guard_signin:
  url:   /login
  param: { module: sfGuardAuth, action: signin }

sf_guard_signout:
  url:   /logout
  param: { module: sfGuardAuth, action: signout }

sf_guard_password:
  url:   /request_password
  param: { module: sfGuardAuth, action: password }

homepage:
  url:   /
  param: { module: posts, action: index }

# generic rules
# please, remove them by adding more specific rules
#default_index:
#  url:   /:module
#  param: { action: index }
#
#default:
#  url:   /:module/:action/*